# Site settings
title               : Marius Avram - Freelance Product-Oriented Fullstack Developer | Web & App Development Expert
description         : > 
                      Freelance Fullstack Software Developer and Product Manager based in Berlin. Expert in Python, JavaScript, FastAPI, and Vue.js for web and app development.
url                 : "https://mariusavram.com"
name                : Marius Avram

resume              : /assets/Marius_Avram_PM-Resume.pdf

github_username     : mariusavram91
linkedin_username   : mariusavram91
email               : me@mariusavram.com

defaults            :
  -
    scope           :
      path          : ""
    values          :
      layout        : "default"

plugins             :
  - jekyll-sitemap
  - jekyll-seo-tag

defaults            :
  -
    scope           :
      path          : "assets/**/*.pdf"
    values          :
      sitemap       : false

robots_txt          : >-
  User-agent: *
  Allow: /