# Site settings
title               : Marius Avram - Product Software Developer
description         : > 
                      Product Software Developer and tech enthusiast based in Berlin with a decade of experience.
url                 : "https://mariusavram.com"
name                : Marius Avram

resume              : /assets/Marius_Avram_PM-Resume.pdf

github_username     : mariusavram91
linkedin_username   : mariusavram91
email               : me@mariusavram.com

defaults            :
  -
    scope           :
      path          : ""
    values          :
      layout        : "default"

plugins             :
  - jekyll-sitemap
  - jekyll-seo-tag

defaults            :
  -
    scope           :
      path          : "assets/**/*.pdf"
    values          :
      sitemap       : false

robots_txt          : >-
  User-agent: *